MassEmail/Controllers/BulkEmailController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net;
using System.IO;
using MassEmail.Models;
using System.Data.Entity;
using System.Text;
using System.Threading.Tasks;
using System.Web;
//using System.Web.Mail;
using System.Net.Mail;


namespace MassEmail.Controllers
{
    public class BulkEmailController : Controller
    {
        // GET: /EmailMessage/
        public ActionResult History()
        {
            return ModelBind();
        }

        // GET EmailMessage/GetGrid
        public ActionResult GetGrid()
        {
            var tak = db.EmailMessages.OrderByDescending(x => x.DateSend).ToArray();
            var users = db.ApplicationUsers.ToArray();

            var result = from c in tak select new string[] { Convert.ToString(c.Id), Convert.ToString(users.FirstOrDefault(i => i.Id == c.FromUserId) != null ? users.FirstOrDefault(i => i.Id == c.FromUserId).FirstName + ' ' + users.FirstOrDefault(i => i.Id == c.FromUserId).LastName : ""), Convert.ToString(c.Id), Convert.ToString(c.Subject), Convert.ToString(c.DateSend) };
            return Json(new { aaData = result }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetGridEmailMembers(int id)
        {
            var tak = db.EmailMembers.Where(i => i.EmailMessageId == id).ToArray();
            var result = from c in tak select new string[] { Convert.ToString(c.Id), Convert.ToString(c.EmailMessage_EmailMessageId.Subject), Convert.ToString(c.ApplicationUser_ToUserId.FirstName + ' ' + c.ApplicationUser_ToUserId.LastName) };
            return Json(new { aaData = result }, JsonRequestBehavior.AllowGet);
        }


        public ActionResult GetGridAttachment(int id)
        {
            var tak = db.EmailAttachments.Where(i => i.EmailMessageId == id).ToArray();

            var result = from c in tak select new string[] { Convert.ToString(c.Id), Convert.ToString(c.EmailMessage_EmailMessageId.Subject), Convert.ToString(c.FileUrl) };
            return Json(new { aaData = result }, JsonRequestBehavior.AllowGet);
        }

        // GET: /EmailMessage/ModelBindIndex
        public ActionResult ModelBindIndex()
        {
            return ModelBind();
        }
        // GET: /EmailMessage/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EmailMessage ObjEmailMessage = db.EmailMessages.Find(id);
            if (ObjEmailMessage == null)
            {
                return HttpNotFound();
            }
            return View(ObjEmailMessage);
        }
        // GET: /EmailMessage/Create
        public ActionResult Create()
        {

            LoadBinding();

            return View();
        }

        private void LoadBinding()
        {
            var UsersList = db.ApplicationUsers.OrderBy(x => x.FirstName);
            int cUserId = Convert.ToInt32(Env.GetUserInfo("userid"));

            StringBuilder sbUser = new StringBuilder();
            sbUser.Append("[");
            //['IT,', 'Sales,', 'Technical,']
            foreach (var item in UsersList.Where(i => i.Id != cUserId).ToArray())
            {
                sbUser.Append("{\"id\":\"" + item.Email + "\", \"name\":\"" + item.FirstName + " " + item.LastName + "\"},");
            }
            sbUser.Append("]");
            ViewBag.UserList = sbUser.ToString();




            StringBuilder sbDepartment = new StringBuilder();
            sbDepartment.Append("[");
            //['IT,', 'Sales,', 'Technical,']
            foreach (var item in db.Departments.OrderBy(x => x.Title).ToArray())
            {
                sbDepartment.Append("{\"id\":\"" + item.Title + "\", \"name\":\"" + item.Title + "\"},");
            }
            sbDepartment.Append("]");
            ViewBag.Departments = sbDepartment.ToString();

            StringBuilder sbFavoriteGroups = new StringBuilder();
            sbFavoriteGroups.Append("[");

            foreach (var item in db.FavoriteGroups.OrderBy(x => x.Name).ToArray())
            {
                sbFavoriteGroups.Append("{\"id\":\"" + item.Id + "\", \"name\":\"" + item.Name + "(" + prepareUsersName(item.Users) + ")" + "\"},");
            }
            sbFavoriteGroups.Append("]");
            ViewBag.FavoriteGroups = sbFavoriteGroups.ToString();

            ViewBag.FromUserId = new SelectList(UsersList, "Id", "Username", cUserId);
        }

        private string prepareUsersName(ICollection<ApplicationUser> users)
        {
            string usersName = "";
            foreach (var user in users)
            {
                usersName += user.CompleteName + ", ";
            }
            return usersName.Remove(usersName.Length - 2);
        }

        // POST: /EmailMessage/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Create(EmailMessage ObjEmailMessage, string toEmails,string toFavoriteEmails, string toDepEmails, HttpPostedFileBase[] filesAttach)
        {
            LoadBinding();
            if (ModelState.IsValid)
            {
                var gs = db.GeneralSettings.ToArray();
                if ((toEmails.Length > 0 || toDepEmails.Length > 0 || toFavoriteEmails.Length > 0))
                {
                    bool isEmailAdded = false;
                    if (toEmails.Length > 0)
                    {
                        db.EmailMessages.Add(ObjEmailMessage);
                        db.SaveChanges();
                        isEmailAdded = true;
                        string filename = "";

                        if (filesAttach.Count() >= 1)
                        {
                            foreach (HttpPostedFileBase file in filesAttach)
                            {
                                if (file != null)
                                {
                                    /*Geting the file name*/
                                    filename = System.IO.Path.GetFileName(file.FileName);
                                    /*Saving the file in server folder*/
                                    file.SaveAs(Server.MapPath("~/Uploads/" + filename));

                                    /*HERE WILL BE YOUR CODE TO SAVE THE FILE DETAIL IN DATA BASE*/
                                    EmailAttachment attach = new EmailAttachment();
                                    attach.FileUrl = filename;
                                    attach.IsDeleted = false;
                                    attach.EmailMessageId = ObjEmailMessage.Id;
                                    db.EmailAttachments.Add(attach);
                                    db.SaveChanges();
                                }
                            }

                        }

                        var AllUsers = db.ApplicationUsers.ToArray();

                        string[] emails = toEmails.Split(',');
                        foreach (var item in emails)
                        {
                            if (item != "")
                            {
                                EmailMember member = new EmailMember();
                                member.EmailMessageId = ObjEmailMessage.Id;
                                member.ToUserId = AllUsers.FirstOrDefault(i => i.Username == item.Trim()).Id;
                                member.IsRead = false;
                                member.DateUpdated = DateTime.Now;
                                db.EmailMembers.Add(member);

                                SendAsync(Env.GetUserInfo("name"), item, ObjEmailMessage.Subject, ObjEmailMessage.MailText, gs, filesAttach);

                                db.SaveChanges();

                            }
                        }
                    }

                    if (toDepEmails.Length > 0)
                    {
                        if (!isEmailAdded)
                        {
                            db.EmailMessages.Add(ObjEmailMessage);
                            db.SaveChanges();
                        }
                        if (filesAttach.Count() > 1)
                        {
                            foreach (HttpPostedFileBase file in filesAttach)
                            {
                                /*Geting the file name*/
                                string filename = System.IO.Path.GetFileName(file.FileName);
                                /*Saving the file in server folder*/
                                file.SaveAs(Server.MapPath("~/Uploads/" + filename));

                                /*HERE WILL BE YOUR CODE TO SAVE THE FILE DETAIL IN DATA BASE*/
                                EmailAttachment attach = new EmailAttachment();
                                attach.FileUrl = filename;
                                attach.IsDeleted = false;
                                attach.EmailMessageId = ObjEmailMessage.Id;
                                db.EmailAttachments.Add(attach);
                                db.SaveChanges();
                            }
                        }
                        string[] departm = toDepEmails.Split(',');
                        foreach (var item in departm)
                        {
                            if (item != "")
                            {
                                var users = db.ApplicationUsers.Where(i => i.Department_DepartmentId.Title == item.Trim()).ToArray();

MassEmail/Views/BulkEmail/Create.cshtml
@model MassEmail.Models.EmailMessage

@{
    ViewBag.Title = "Toplu Email Oluştur";
    if (Ajax.IsThisAjaxRequest())
    {
        Layout = null;
    }
}
@section ScriptsOrCss{
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    </head>

    <script src="~/Content/ckEditor/ckeditor.js"></script>
    <link href="~/Content/ckEditor/samples/sample.css" rel="stylesheet" />
    <link href="~/Content/tagsinput/magicsuggest-min.css" rel="stylesheet">
    <script src="~/Content/tagsinput/magicsuggest-min.js"></script>
}

<script type="text/javascript">
    $(function () {
        var ms1 = $('#ms1').magicSuggest({
            data: @Html.Raw(ViewBag.UserList),
            expandOnFocus:true
        });

        var departm = $('#departm').magicSuggest({
            data: @Html.Raw(ViewBag.Departments)
        });

        var favorite = $('#favorite').magicSuggest({
            data: @Html.Raw(ViewBag.FavoriteGroups)
        });

        $(ms1).on('selectionchange', function(){
            $("#toEmails").val(this.getValue());
        });

        $(departm).on('selectionchange', function(){
            $("#toDepEmails").val(this.getValue());
        });

        $(favorite).on('selectionchange', function(){
            $("#toFavoriteEmails").val(this.getValue());
        });
    });

    $(document).ready(function () {


        //$(document).mouseover(function () {
        //    $("#toEmails").val($("#ms1").text());
        //});

        //$(document).mouseover(function () {
        //    $("#toDepEmails").val($("#departm").text());
        //});

        //$("#ms1").click(function () {
        //    $("#toEmails").val($("#ms1").text());
        //});

        //$("#departm").click(function () {
        //    $("#toDepEmails").val($("#departm").text());
        //});

        $(".usr").click(function () {
            $("#ms1").show();
            $("#favorite").hide();
            $("#departm").hide();
        });

        $(".dep").click(function () {
            $("#ms1").hide();
            $("#favorite").hide();
            $("#departm").show();
        });

        $(".fav").click(function () {
            $("#ms1").hide();
            $("#favorite").show();
            $("#departm").hide();
        });

    });


</script>
<section class="content-header">
    <h1>
        <meta charset="UTF-8" />
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    </h1>
</section>

@using (Html.BeginForm("Create", "BulkEmail", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
          <!-- Main content -->
    <section class="content">
        <!-- Small boxes (Stat box) -->
        <div class="row">
            <div class="panel" height: 765px;>
                <div class="panel-header">
                    <h3 class="box-title"> Email Oluştur </h3>
                </div><!-- /.box-header -->
                <!-- form start -->
                <div role="form">
                    <div class="panel-content">

                        @if (ViewBag.Msg != null)
                            {
                            <div class="alert alert-danger alert-dismissable">
                                <i class="fa fa-ban"></i>
                                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                                <b>Uyarı! </b> @ViewBag.Msg


                            </div>
                            }


                        @if (ViewBag.Success != null)
                            {
                            <div class="alert alert-success alert-dismissable">
                                <i class="fa fa-ban"></i>
                                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                                <b>Başarıyla Gönderildi! </b> @ViewBag.Success


                            </div>
                            }




                        <div class="alert alert-danger alert-dismissable" style="display:@(this.ViewData.ModelState.IsValid ? "none" : "")">
                            <i class="fa fa-ban"></i>
                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>

                            @foreach (var key in this.ViewData.ModelState.Keys)
                                {
                                    foreach (var err in this.ViewData.ModelState[key].Errors)
                                    {
                                <b>Uyarı! </b> @err.ErrorMessage
                                <br />
                                    }
                                }
                            @Html.ValidationSummary(true)
                        </div>

                        <div class="form-group">

                            <div class="switch-field" style="margin-left:-40px; margin-top:-45px; line-height:1.028571;">
                                <input class="usr" type="radio" id="switch_3_left" name="s1" value="Users" checked />
                                <label class="usr" for="switch_3_left">Kullanıcı</label>
                                <input class="dep" type="radio" id="switch_3_center" name="s1" value="Departments" />
                                <label class="dep" for="switch_3_center">Kurum</label>
                                <input class="fav" type="radio" id="switch_3_right" name="s1" value="FavoriteGroup" />
                                <label class="fav" for="switch_3_right">Favori Grup</label>
                            </div>



                        </div>

                        <div class="form-group" style="margin-top:-45px;">
                            <label>Alıcı</label>
                            <div id="ms1" class="form-control" style="padding: 0px !important;padding-left: 10px !important;width:50%;"></div>
                            <div id="departm" class="form-control" style="display:none; padding: 0px !important;padding-left: 10px !important;width:50%;"></div>
                            <div id="favorite" class="form-control" style="display:none; padding: 0px !important;padding-left: 10px !important;width:50%;"></div>
                        </div>

                        <div class="form-group" style="display:none;">
                            @Html.LabelFor(model => model.FromUserId, new { @class = "" })
                            @Html.DropDownList("FromUserId", " -Seçiniz- ")
                            @Html.ValidationMessageFor(model => model.FromUserId)

                            &nbsp;&nbsp; <a data-ajax="true" data-ajax-begin="prepareModalDialog('AddMore')" data-ajax-failure="clearModalDialog('AddMore');alert('Ajax call failed')" data-ajax-method="GET" data-ajax-mode="replace" data-ajax-success="openModalDialog('AddMore', 'Add')" data-ajax-update="#AddMore" href="~/ApplicationUser/Create">
                                <img src="~/Content/ModelPopup/Plus.png" />
                            </a>
                        </div>

                        <div class="form-group" style="display:none;">

                            <input id="toEmails" type="text" name="toEmails" />
                            <input id="toDepEmails" type="text" name="toDepEmails" />
                            <input id="toFavoriteEmails" type="text" name="toFavoriteEmails" />
                        </div>

                        <div class="form-group" style=" ">

                            <input type="file" name="filesAttach" value="" multiple="multiple" />

                        </div>



                        <div class="form-group">
                            @Html.LabelFor(model => model.Subject, new { @class = "" })
                            @Html.TextBoxFor(model => model.Subject, new { @class = "form-control", @placeholder = "Konu" }) @Html.ValidationMessageFor(model => model.Subject)
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.MailText, new { @class = "" })
                            @Html.TextAreaFor(model => model.MailText, new { @class = "ckeditor" }) @Html.ValidationMessageFor(model => model.MailText)
                        </div>
                        <div class="form-group">
                            @Html.Hidden("DateSend", DateTime.Now) @Html.ValidationMessageFor(model => model.DateSend)
                        </div>
                        <div class="form-group" style="display:none;">
                            <input type="hidden" value="false" name="IsDelete" />
                        </div>

                    </div>
                    <div>
                        <input type="submit" style="margin-left:20px;" value="Gönder" class="btn btn-primary" />
                        @Html.ActionLink("Email Geçmiş", "History", null, new { @class = "btn btn-primary" })
                    </div>
                </div>
            </div>
        </div>
    </section>
}
<script type="text/javascript">
    $(document).ready(function (){
        $("#loading-div-background").css({ opacity: 1.0 });
        $("#loading-div-background").hide();
    });

    function ShowProgressAnimation(){
        $("#loading-div-background").show();
    }
</script>
<style>
    .text-box.single-line {
        text-transform: uppercase;
    }

    .switch-field {
        font-family: "Lucida Grande", Tahoma, Verdana, sans-serif;
        padding: 40px;
        overflow: hidden;
    }

    .switch-title {
        margin-bottom: 6px;
    }

    .switch-field input {
        display: none;
    }

    .switch-field label {
        float: left;
    }

    .switch-field label {
        display: inline-block;
        width: 155px;
        background-color: #e4e4e4;
        color: rgba(0, 0, 0, 0.6);
        font-size: 14px;
        font-weight: normal;
        text-align: center;
        text-shadow: none;
        padding: 6px 14px;
        border: 1px solid rgba(0, 0, 0, 0.2);
        -webkit-box-shadow: inset 0 1px 3px rgba(0, 0, 0, 0.3), 0 1px rgba(255, 255, 255, 0.1);
        box-shadow: inset 0 1px 3px rgba(0, 0, 0, 0.3), 0 1px rgba(255, 255, 255, 0.1);
        -webkit-transition: all 0.1s ease-in-out;
        -moz-transition: all 0.1s ease-in-out;
        -ms-transition: all 0.1s ease-in-out;
        -o-transition: all 0.1s ease-in-out;
        transition: all 0.1s ease-in-out;
    }

        .switch-field label:hover {
            cursor: pointer;
        }

    .switch-field input:checked + label {
        background-color: #3AF;
        -webkit-box-shadow: none;
        box-shadow: none;
    }

    .switch-field label:first-of-type {
        border-radius: 4px 0 0 4px;
    }

    .switch-field label:last-of-type {
        border-radius: 0 4px 4px 0;
    }
    .text-box.single-line {
        text-transform: uppercase;
    }
</style>

MassEmail/Views/BulkEmail/Delete.cshtml
@model MassEmail.Models.EmailMessage

@{
    ViewBag.Title = "Silmek istediğinize eminmisiniz?";
    if (Ajax.IsThisAjaxRequest())
    {
        Layout = null;
    }
}
<head>
<meta charset="UTF-8"/>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
</head>
<section class="content-header">
    <h1>
    <meta charset="UTF-8"/>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        @ViewBag.Title
    </h1>
</section>

<section class="content">
    <!-- Small boxes (Stat box) -->
    <div class="row">
        <div class="col-xs-12">

            <div class="panel">
                <div class="panel-header">
                    <h3 class="box-title">Email Mesaj Detay</h3>
                </div><!-- /.box-header -->
                <div class="panel-content">

                    <div class="widget-sec">
                        <div class="streaming-table">
                            <table class="table table-striped table-bordered">

                                <tr>
                                    <td>Gönderen ID</td>
                                    <td>@Html.DisplayFor(model => model.FromUserId)</td>
                                </tr>
                                <tr>
                                    <td>Konu</td>
                                    <td>@Html.DisplayFor(model => model.Subject)</td>
                                </tr>
                                <tr>
                                    <td> Mail Mesaj</td>
                                    <td>  @Html.Raw(Model.MailText)</td>
                                </tr>
                                <tr>
                                    <td>Tarih</td>
                                    <td>@Html.DisplayFor(model => model.DateSend)</td>
                                </tr>
                                <tr>
                                    <td>Silindi</td>
                                    <td>@Html.DisplayFor(model => model.IsDelete)</td>
                                </tr>


                            </table>
                            <div class="panel-footer">

                                @using (Html.BeginForm())
                                {
                                    @Html.AntiForgeryToken()

                                    <input type="submit" value="Sil" class="btn btn-primary" />
                                    @Html.ActionLink("Liste", "Index", null, new { @class = "btn btn-primary" })
                                }
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>




MassEmail/Views/BulkEmail/Details.cshtml
@model MassEmail.Models.EmailMessage

@{
    
    if (Ajax.IsThisAjaxRequest())
    {
        Layout = null;
    }
}
<section class="content-header">
    <h1>

    </h1>
</section>
<section class="content">
    <!-- Small boxes (Stat box) -->
    <div class="row">
        <div class="col-xs-12">

            <div class="panel">
                <div class="panel-header">
                    <h3 class="box-title">Email Mesaj Detay</h3>
                </div><!-- /.box-header -->
                <div class="panel-content">

                    <div class="widget-sec">
                        <div class="streaming-table">
                            <table class="table table-striped table-bordered">

                                <tr>
                                    <td>Gönderen ID</td>
                                    <td>@Html.DisplayFor(model => model.FromUserId)</td>
                                </tr>
                                <tr>
                                    <td>Konu</td>
                                    <td>@Html.DisplayFor(model => model.Subject)</td>
                                </tr>
                                <tr>
                                    <td> Mail Mesaj</td>
                                    <td>  @Html.Raw(Model.MailText)</td>
                                </tr>
                                <tr>
                                    <td>Tarih</td>
                                    <td>@Html.DisplayFor(model => model.DateSend)</td>
                                </tr>
                                <tr>
                                    <td>Silindi</td>
                                    <td>@Html.DisplayFor(model => model.IsDelete)</td>
                                </tr>

 
                            </table>
                            <div class="panel-footer">
                                @Ajax.ModalDialogActionLink("Düzenle", "Edit/" + Model.Id, "Edit", "btn btn-primary") 
                                
                                @Html.ActionLink("Liste", "Index", null, new { @class = "btn btn-primary" })
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>




MassEmail/Views/BulkEmail/Edit.cshtml
@model MassEmail.Models.EmailMessage

@{
    
    if (Ajax.IsThisAjaxRequest())
    {
        Layout = null;
    }
}
@section ScriptsOrCss{
<head>
    <meta charset="UTF-8" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
</head>
<script src="~/Content/ckEditor/ckeditor.js"></script>
<link href="~/Content/ckEditor/samples/sample.css" rel="stylesheet" />
}
<section class="content-header">
    <h1>
        <meta charset="UTF-8" />
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        @ViewBag.Title
    </h1>
</section>
@using (Html.BeginForm("Edit", "EmailMessage", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <section class="content">
        <div class="row">
                <div class="panel">
                    <div class="panel-header">
                        <h3 class="box-title">Kullanıcı Düzenle</h3>
                    </div><!-- /.box-header -->
                    <!-- form start -->
                    <div role="form">
                        <div class="panel-content">
                            <div class="alert alert-danger alert-dismissable" style="display:@(this.ViewData.ModelState.IsValid ? "none" : "")">
                                <i class="fa fa-ban"></i>
                                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>

                                @foreach (var key in this.ViewData.ModelState.Keys)
                                {
                                    foreach (var err in this.ViewData.ModelState[key].Errors)
                                    {
                                        <b>Uyarı! </b> @err.ErrorMessage
                                        <br />
                                    }
                                }
                            </div>



                            <div class="form-group">
                                @Html.LabelFor(model => model.FromUserId, new { @class = "" })
                                @Html.DropDownList("FromUserId"," -Seçiniz- ") @Html.ValidationMessageFor(model => model.FromUserId)
                                
                                &nbsp;&nbsp; <a data-ajax="true" data-ajax-begin="prepareModalDialog('AddMore')" data-ajax-failure="clearModalDialog('AddMore');alert('Ajax call failed')" data-ajax-method="GET" data-ajax-mode="replace" data-ajax-success="openModalDialog('AddMore', 'Add')" data-ajax-update="#AddMore" href="~/ApplicationUser/Create">
                                     <img src="~/Content/ModelPopup/Plus.png" />
                                </a>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.Subject, new { @class = "" })
                                @Html.EditorFor(model => model.Subject) @Html.ValidationMessageFor(model => model.Subject)
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.MailText, new { @class = "" })
                                @Html.TextAreaFor(model => model.MailText, new { @class = "ckeditor" }) @Html.ValidationMessageFor(model => model.MailText)
                            </div>
                            <div class="form-group">
                                @Html.Hidden("DateSend", DateTime.Now) @Html.ValidationMessageFor(model => model.DateSend)
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.IsDelete, new { @class = "" })
                                @Html.EditorFor(model => model.IsDelete) @Html.ValidationMessageFor(model => model.IsDelete)
                            </div>


                        </div><!-- /.box-body -->
                        <div class="panel-footer">
                            <input type="submit" value="Kaydet" class="btn btn-primary" />
                            @Html.ActionLink("Liste", "Index", null, new { @class = "btn btn-primary" })
                        </div>
                    </div>
                </div>
        </div>
    </section>

}

