MassEmail/Models/FavoriteGroup.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MassEmail.Models
{
    public class FavoriteGroup
    {
        public FavoriteGroup()
        {
            this.Users = new List<ApplicationUser>();
        }
        public int Id { get; set; }

        [Required]
        public string Name { get; set; }

        public virtual ICollection<ApplicationUser> Users { get; set; }
    }
}

MassEmail/Controllers/FavoriteGroupController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.IO;
using MassEmail.Models;
using System.Text;
using System.Threading.Tasks;
using System.Net.Mail;
using Microsoft.AspNet.SignalR;
using MassEmail.ChatClass;
using MassEmail.Helper;
using MassEmail.Controllers.Filters;
using MassEmail.Models.Comparer;

namespace MassEmail.Controllers
{
    [AuthorizationAndRoleFilter(accessRole=AccessRole.FavoriteGroup)]
    public class FavoriteGroupController : Controller
    {
        private SIContext db;

        public FavoriteGroupController()
        {
            this.db = new SIContext();
        }
        // GET: FavoriteGroup
        public ActionResult Index()
        {
            var FavoriteGroups = db.FavoriteGroups.ToList();
            return View(FavoriteGroups);
        }
        public ActionResult Create()
        {
            var users = new SelectList(db.ApplicationUsers.ToList(), "Id", "CompleteName");
            ViewBag.UserId = users;
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Create(FavoriteGroup objFavoriteGroup)
        {
            if (ModelState.IsValid)
            {
                var users = Request.Form["UserId"].Split(',');
                foreach (var user in users)
                {
                    objFavoriteGroup.Users.Add(db.ApplicationUsers.Find(Convert.ToInt32(user)));
                }
                db.FavoriteGroups.Add(objFavoriteGroup);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.DepartmentId = new SelectList(db.ApplicationUsers.ToList(), "Id", "CompleteName");

            return View(objFavoriteGroup);
        }
        public ActionResult MyGroups()
        {
            return View();
        }
        public ActionResult GetMyGroups()
        {
            ApplicationUser user = db.ApplicationUsers.Find(Convert.ToInt32(Env.GetUserInfo("userid")));
            var groups = db.FavoriteGroups.OrderBy(x => x.Name).ToArray().Where(f => f.Users.Contains(user, new UserComparer())).ToList();
            var result = from c in groups select new string[] { c.Id.ToString(), Convert.ToString(c.Name), prepareUsersName(c.Users) };
            return Json(new { aaData = result }, JsonRequestBehavior.AllowGet);
        }
        public ActionResult GetGrid()
        {
            var groups = db.FavoriteGroups.OrderBy(x => x.Name).ToArray();
            var result = from c in groups select new string[] { c.Id.ToString(), Convert.ToString(c.Name), prepareUsersName(c.Users) };
            return Json(new { aaData = result }, JsonRequestBehavior.AllowGet);
        }

        private string prepareUsersName(ICollection<ApplicationUser> users)
        {
            string usersName = "";
            foreach (var user in users)
            {
                usersName += user.CompleteName + ", ";
            }
            return usersName.Remove(usersName.Length - 2);
        }
    }
}

MassEmail/Views/FavoriteGroup/Create.cshtml
@model MassEmail.Models.FavoriteGroup

@{
    if (Ajax.IsThisAjaxRequest())
    {
        Layout = null;
    }
}
@section ScriptsOrCss{
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    </head>
    <script src="~/Content/ckEditor/ckeditor.js"></script>
    <link href="~/Content/ckEditor/samples/sample.css" rel="stylesheet" />
    <style>
        .select2{
            width: 100% !important
        }
    </style>
}
<section class="content-header">
    <h1>
        <meta charset="UTF-8" />
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    </h1>
</section>
@using (Html.BeginForm("Create", "FavoriteGroup", FormMethod.Post, new { enctype = "multipart/form-data", id = "form1" }))
{
    @Html.AntiForgeryToken()
    <section class="content">
        <div class="row">
            <div class="panel">
                <div class="panel-header">
                    <h3 class="box-title">Grup Oluştur</h3>
                </div>
                <div role="form" class="panel-content">
                        @if (ViewBag.Success != null)
                        {
                            <div class="alert alert-success alert-dismissable">
                                <i class="fa fa-ban"></i>
                                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                                <b>Başarılı! </b> @ViewBag.Success
                            </div>
                        }

                        <div class="alert alert-danger alert-dismissable" style="display:@(this.ViewData.ModelState.IsValid ? "none" : "")">
                            <i class="fa fa-ban"></i>
                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>

                            @foreach (var key in this.ViewData.ModelState.Keys)
                            {
                                foreach (var err in this.ViewData.ModelState[key].Errors)
                                {
                                    <b>Uyarı! </b> @err.ErrorMessage
                                    <br />
                                }
                            }
                            @Html.ValidationSummary(true)
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Name, "Grup Adı")
                            @Html.TextBoxFor(model => model.Name, new { required = "required", @class = "form-control" }) @Html.ValidationMessageFor(model => model.Name)

                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.Users, "Kullanıcı Listesi")
                            @Html.DropDownList("UserId", null, " -Seçiniz-", new { required = "required", multiple = "", @class = "selectpicker" })
                        </div>
                    <div>
                        <input type="submit" value="Oluştur" class="btn btn-primary" id="submit1" />
                        @Html.ActionLink("Liste", "Index", null, new { @class = "btn btn-primary" })
                    </div>
                </div>
            </div>
        </div>
    </section>
}

MassEmail/Views/FavoriteGroup/Index.cshtml
@model IEnumerable<MassEmail.Models.FavoriteGroup>

@{
    ViewBag.Title = "Favori Grup";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section ScriptsOrCss
{
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    </head>
    <script src="~/Content/DataTable/js/plugins/dataTables/jquery.dataTables.js"></script>
    <script src="~/Content/DataTable/js/plugins/dataTables/dataTables.bootstrap.js"></script>
    <link href="~/Content/DataTable/plugins/dataTables.bootstrap.css" rel="stylesheet" />
    <script src="~/Content/DataTable/js/plugins/dataTables.responsive.min.js"></script>
    <script src="~/Content/DataTable/js/plugins/dataTables/jquery.dataTable.minNew.js"></script>
    <script type="text/javascript" src="~/Content/HtmlExprt/tableExport.js"></script>
    <script type="text/javascript" src="~/Content/HtmlExprt/jquery.base64.js"></script>
    <script type="text/javascript" src="~/Content/HtmlExprt/html2canvas.js"></script>
    <script type="text/javascript" src="~/Content/HtmlExprt/jspdf/libs/sprintf.js"></script>
    <script type="text/javascript" src="~/Content/HtmlExprt/jspdf/jspdf.js"></script>
    <script type="text/javascript" src="~/Content/HtmlExprt/jspdf/libs/base64.js"></script>

    <script src="~/Content/fancybox/helpers/jquery.fancybox-buttons.js?v=1.0.5"></script>
    <script type="text/javascript" src="~/Content/fancybox/helpers/jquery.fancybox-media.js?v=1.0.5"></script>
    <script src="~/Content/fancybox/jquery.fancybox.pack.js"></script>
    <script src="~/Content/fancybox/jquery.fancybox.js?v=2.1.4"></script>
    <link href="~/Content/fancybox/jquery.fancybox.css" rel="stylesheet" />
    <link href="~/Content/fancybox/helpers/jquery.fancybox-buttons.css" rel="stylesheet" />
    <link href="~/Content/DataTable/js/plugins/responsive.dataTables.min.css" rel="stylesheet" />

    <link href="~/Content/bildirimobile.css" rel="stylesheet" />

}
<section class="content-header">
    <h1>
        <meta charset="UTF-8" />
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    </h1>
</section>
<section class="content">
    <div class="row">
        <div class="panel mobile-noshow">
            <div class="panel-content">
                <div class="margin">
                    <div class="btn-group">
                        @Ajax.ModalDialogActionLink("Oluştur", "Create", "Create ", "btn btn-success")
                    </div>
                </div>
            </div>
        </div>
        <div class="panel">
            <div class="panel-header">
                <h3 class="box-title">@ViewBag.Title</h3>
            </div>
            <div class="panel-content">
                <div class="margin">
                    <div class="streaming-table">
                        <span id="found" class="label label-info"></span>
                        <table id="tbApplicationUser" class="table table-mobile" width="100%" cellspacing="0">
                            <thead>
                                <tr>
                                    <th></th>
                                    <th> Group adı</th>
                                    <th> Kullanıcılar </th>
                                </tr>
                            </thead>
                            <tbody></tbody>
                        </table>

                        <div id="summary">
                            <div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<script type="text/javascript">

    $(document).ready(function () {
        var oTableApplicationUser = "";
        var ControlerNameApplicationUser = "@Url.Content("~/FavoriteGroup")";
        oTableApplicationUser = $("#tbApplicationUser").dataTable({
            "scrollX": true,
            "bRetrieve": true,
            "fnInitComplete": function (oSettings, json) {
                configurerows();
            },
            "fnDrawCallback": function (oSettings){
                configurerows();
            },
            "bProcessing": true,
            "aaSorting": [[3, 'asc']],
            "sAjaxSource": "@Url.Content("~/FavoriteGroup/GetGrid")",
            "aoColumns": [

            {
                "mRender": function (oObj, type, row) {


                   
                   var buttons = "<a class=\"btn btn-sm btn-danger\" href=" + ControlerNameApplicationUser + "/Delete/" + row[0] + " data-ajax-update=\"#SkDelete\" data-ajax-success=\"openModalDialog('SkDelete', 'Delete')\" data-ajax-mode=\"replace\" data-ajax-method=\"GET\" data-ajax-failure=\"clearModalDialog('SkDelete');alert('Ajax call failed')\" data-ajax-begin=\"prepareModalDialog('SkDelete')\" data-ajax=\"true\"><i class=\"fa fa-bitbucket f18\"></i></a>";

                    return buttons;

                }

            }

, {
    "mRender": function (oObj, type, row) {
        return " " + oObj + " </a>";
    }
}, {}
, {}
, {}
, {}

            ]

        });
        var table = $('#tbApplicationUser').DataTable({});

        $('a.toggle-vis').on('click', function (e) {
            e.preventDefault();
            var column = table.column($(this).attr('data-column'));
            column.visible(!column.visible());
        });
    });
    function configurerows() {
        $trs = $('.table-mobile tbody tr');
        $.each($trs, function (id, tr) {
            $(tr).find('td:eq(0)').addClass('mobile-noshow');
            $(tr).find('td:eq(1)').attr('data-label', 'Name');
            $(tr).find('td:eq(2)').attr('data-label', 'Users');
        });
    }
    function ExportExcel() {
        window.location.href = "http://http://aykome.aydin.bel.tr:84//ApplicationUser/GetExcel"

        //$.ajax({
        //    type: "POST",
        //    url: "/ApplicationUser/GetExcel",
        //    success: function () {
        //        if (response.aaData != null) {


        //        } else {
        //                          }
        //    },

        //});

    }
</script>


MassEmail/Views/FavoriteGroup/MyGroups.cshtml
@model IEnumerable<MassEmail.Models.FavoriteGroup>

@{
    ViewBag.Title = "My Groups";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section ScriptsOrCss
{
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    </head>
    <script src="~/Content/DataTable/js/plugins/dataTables/jquery.dataTables.js"></script>
    <script src="~/Content/DataTable/js/plugins/dataTables/dataTables.bootstrap.js"></script>
    <link href="~/Content/DataTable/plugins/dataTables.bootstrap.css" rel="stylesheet" />
    <script src="~/Content/DataTable/js/plugins/dataTables.responsive.min.js"></script>
    <script src="~/Content/DataTable/js/plugins/dataTables/jquery.dataTable.minNew.js"></script>
    <script type="text/javascript" src="~/Content/HtmlExprt/tableExport.js"></script>
    <script type="text/javascript" src="~/Content/HtmlExprt/jquery.base64.js"></script>
    <script type="text/javascript" src="~/Content/HtmlExprt/html2canvas.js"></script>
    <script type="text/javascript" src="~/Content/HtmlExprt/jspdf/libs/sprintf.js"></script>
    <script type="text/javascript" src="~/Content/HtmlExprt/jspdf/jspdf.js"></script>
    <script type="text/javascript" src="~/Content/HtmlExprt/jspdf/libs/base64.js"></script>

    <script src="~/Content/fancybox/helpers/jquery.fancybox-buttons.js?v=1.0.5"></script>
    <script type="text/javascript" src="~/Content/fancybox/helpers/jquery.fancybox-media.js?v=1.0.5"></script>
    <script src="~/Content/fancybox/jquery.fancybox.pack.js"></script>
    <script src="~/Content/fancybox/jquery.fancybox.js?v=2.1.4"></script>
    <link href="~/Content/fancybox/jquery.fancybox.css" rel="stylesheet" />
    <link href="~/Content/fancybox/helpers/jquery.fancybox-buttons.css" rel="stylesheet" />
    <link href="~/Content/DataTable/js/plugins/responsive.dataTables.min.css" rel="stylesheet" />

    <link href="~/Content/bildirimobile.css" rel="stylesheet" />

}
<section class="content-header">
    <h1>
        <meta charset="UTF-8" />
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    </h1>
</section>

<section class="content">
    <!-- Small boxes (Stat box) -->
    <div class="row">
        <div class="panel mobile-noshow" style="display:none;">
            <div class="panel-content">
                <!-- Split button -->
                <div class="margin">
                    <div class="btn-group">
                        <button type="button" class="btn btn-blue dropdown-toggle" data-toggle="dropdown">
                            Filtre <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu" role="menu">
                            <li><a class="toggle-vis" data-column="0">Eylemler</a></li>
                            <li><a class="toggle-vis" data-column="1">ID</a></li>
                            <li><a class="toggle-vis" data-column="2">Konu</a></li>
                            <li><a class="toggle-vis" data-column="3">Alıcı ID</a></li>
                            <li><a class="toggle-vis" data-column="4">Okundu</a></li>

                        </ul>
                    </div>
                    <div class="btn-group">
                        <button type="button" class="btn btn-blue" onclick="$('#tbAnnouncementMember').tableExport({ type: 'pdf', escape: 'false' });"><i class="fa fa-file-pdf-o f18"></i>Çıkart PDF<div class="ripple-wrapper"></div></button>
                    </div>
                    <div class="btn-group">
                        <button type="button" class="btn btn-blue" onclick="ExportExcel();"><i class="fa fa-file-excel-o f18"></i>Çıkart Excel<div class="ripple-wrapper"></div></button>
                    </div>
                    <div class="btn-group">
                        <button type="button" class="btn btn-blue" onclick="$('#tbAnnouncementMember').tableExport({ type: 'doc', escape: 'false' });"><i class="fa fa-file-word-o f18"></i>Çıkart Word<div class="ripple-wrapper"></div></button>
                    </div>
                    <div class="btn-group">
                        <button type="button" class="btn btn-blue" onclick="$('#tbAnnouncementMember').tableExport({ type: 'csv', escape: 'false' });"><i class="fa fa-file-archive-o f18"></i>Çıkart CSV<div class="ripple-wrapper"></div></button>
                    </div>
                    <div class="btn-group">
                        <button type="button" class="btn btn-blue dropdown-toggle" data-toggle="dropdown">
                            Çıkart <span class="caret"></span>
                        </button>
                        <span class="dropdown-arrow"></span>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="#" onclick="$('#tbAnnouncementMember').tableExport({ type: 'powerpoint', escape: 'false' });"> <img src='~/Content/HtmlExprt/icons/ppt.png' style="height:25px !important;margin:3px;"> PowerPoint</a></li>
                            <li><a href="#" onclick="$('#tbAnnouncementMember').tableExport({ type: 'json', escape: 'false' });"> <img src='~/Content/HtmlExprt/icons/json.png' style="height:25px !important;margin:3px;"> JSON</a></li>
                            <li><a href="#" onclick="$('#tbAnnouncementMember').tableExport({ type: 'xml', escape: 'false' });"> <img src='~/Content/HtmlExprt/icons/xml.png' style="height:25px !important;margin:3px;"> XML</a></li>
                            <li><a href="#" onclick="$('#tbAnnouncementMember').tableExport({ type: 'sql' });"> <img src='~/Content/HtmlExprt/icons/sql.png' style="height:25px !important;margin:3px;"> SQL</a></li>
                            <li><a href="#" onclick="$('#tbAnnouncementMember').tableExport({ type: 'txt', escape: 'false' });"> <img src='~/Content/HtmlExprt/icons/txt.png' style="height:25px !important;margin:3px;"> TXT</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="panel">
            <div class="panel-header">
                <h3 class="box-title">  Kayıtlar</h3>
            </div><!-- /.box-header -->
            <div class="panel-content">
                <div class="margin">
                    <div class="streaming-table">
                        <span id="found" class="label label-info"></span>
                        <table id="tbAnnouncementMember" class="table table-striped table-bordered table-mobile">
                            <thead>
                                <tr>
                                    <th></th>
                                    <th> Group adı </th>
                                    <th> Kullanıcılar </th>
                                </tr>
                            </thead>
                            <tbody></tbody>
                        </table>

                        <div id="summary">
                            <div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <a href="#popup" class="fancy" style="display:none" id="fire"></a>
    <div class="scrollbar" id="popup" style="height:200px !important;overflow-y:auto;width:250px;"></div>
    <a href="#popup1" class="fancy1" style="display:none" id="fire1"></a>
    <div class="scrollbar" id="popup1" style="min-width:150px;overflow-y:auto;display:none">
        <div><h2 style="font-style:normal;">Etkinlik</h2></div>
        <div>
            <table id="pcontents" class="table table-striped table-bordered">
                <tr>
                    <td>Konu</td>
                    <td id="sub"></td>
                </tr>
                <tr>
                    <td>Mesaj</td>
                    <td id="body"></td>
                </tr>
            </table>

        </div>

    </div>
</section>





<script type="text/javascript">

    $(document).ready(function () {
        var oTableAnnouncementMember = "";
        var ControlerName = "@Url.Content("~/FavoriteGroup")";
        // debugger;
        oTableAnnouncementMember = $("#tbAnnouncementMember").dataTable({
            responsive: true,
            "bautoWidth": false,
            "bRetrieve": true,
            "fnInitComplete": function (oSettings, json) {
                configurerows();
            },
            "fnDrawCallback": function (oSettings) {
                configurerows();
            },
            "bProcessing": true,
            "sAjaxSource": "@Url.Content("~/FavoriteGroup/GetMyGroups")",
           

        });

        $('a.toggle-vis').on('click', function (e) {
            e.preventDefault();
            var column = table.column($(this).attr('data-column'));
            column.visible(!column.visible());
        });
    });
    $(document).ready(function () {
        $(".fancy").fancybox({
            width: '100%',
            height: '200px',
        });
    });
    $(document).ready(function () {
        $(".fancy1").fancybox({
            width: '100%',
            height: '200px',
        });
    });
    function expand1(xid) {

        $.ajax({
            type: "POST",
            url: "/EventMember/GetGridAll1",
            data: { id: xid },
            success: function (response) {
                $.each(response.aaData, function (id, option) {
                    $("#sub").append(option.sub);
                    $("#body").append(option.body);
                    //document.getElementById("sub").innerHTML = response.aaData;
                    //document.getElementById("body").innerHTML = response.body;

                    $("#fire1").click();
                });
            },
            error: function (error) {
                alert(error);
                console.log(error);
            }
        });
        $('#sub').html("");
        $('#body').html("");
    }
    function configurerows() {
        $trs = $('.table-mobile tbody tr');
        $.each($trs, function (id, tr) {
            $(tr).find('td:eq(0)').addClass('mobile-noshow');
            $(tr).find('td:eq(1)').attr('data-label', 'Name');
            $(tr).find('td:eq(2)').attr('data-label', 'Users');
        });
    }
</script>

<style>
    .table > thead > tr > th, .table > tbody > tr > th, .table > tfoot > tr > th, .table > thead > tr > td, .table > tbody > tr > td, .table > tfoot > tr > td {
        vertical-align: text-bottom;
    }

    .table.dataTable, table.dataTable td, table.dataTable th {
        max-width: 100px;
        overflow-x: hidden;
        overflow-y: hidden;
        text-overflow: ellipsis;
        white-space: nowrap;
    }
</style>