MassEmail/Controllers/AnnouncementController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.IO;
using MassEmail.Models;
using System.Text;
using System.Threading.Tasks;
using System.Net.Mail;
using Microsoft.AspNet.SignalR;
using MassEmail.ChatClass;
using MassEmail.Helper;
using MassEmail.Controllers.Filters;

namespace MassEmail.Controllers
{
    
    public class AnnouncementController : Controller
    {
        // GET: /Announcement/
        [AuthorizationAndRoleFilter(accessRole=AccessRole.Announcement)]
        public ActionResult Index()
        {
            return ModelBind();
        }

        // GET Announcement/GetGrid
        public ActionResult GetGrid()
        {
            var tak = db.Announcements.Take(50).ToArray().OrderByDescending(x => x.DateSend);
            var users = db.ApplicationUsers.ToArray();
            var us = db.AnnouncementMembers.ToArray();
            //BRB
            var result = from c in tak select new string[] { 
                Convert.ToString(c.Id), 
                Convert.ToString("<a style='cursor:pointer !important;' onclick='expand1(" + c.Id + ")'>" + c.Subject + "</a>"), 
                Convert.ToString(c.DateSend), 
                Convert.ToString(c.FileUrl), 
                Convert.ToString(users.FirstOrDefault(i => i.Id == c.FromUserId) != null ? users.FirstOrDefault(i => i.Id == c.FromUserId).FirstName + ' ' + users.FirstOrDefault(i => i.Id == c.FromUserId).LastName : ""), 
                newfunc(c), };

            var dsdsf = result = result.Skip(Math.Max(0, result.Count() - 20)).ToList();

            return Json(new { aaData = result }, JsonRequestBehavior.AllowGet);
        }

        private string sfunc(Announcement c)
        {
            string tu = "";
            var data = c.AnnouncementMember_EmailMessageIds;
            foreach (var item in data)
            {
                
                tu += item.ApplicationUser_ToUserId.FirstName + ' ' + item.ApplicationUser_ToUserId.LastName;
                tu += " , ";
            }
            tu = tu.TrimEnd(' ');
            tu = tu.TrimEnd(',');
            

            return tu;
        }

        public ActionResult GetGridAll1(Announcement d)
        {
            var data = d.AnnouncementMember_EmailMessageIds;
            var tak = db.Announcements.ToArray();

            var result = from c in db.Announcements
                         where c.Id == d.Id
                         select new
                         {
                sub = c.Subject,
            body = c.MailText,
            };
            return Json(new { aaData = result }, JsonRequestBehavior.AllowGet);
        }
        public ActionResult GetGridAll(Announcement d)
        {

            var data = d.AnnouncementMember_EmailMessageIds;
            var tak = from c in db.AnnouncementMembers where c.EmailMessageId==d.Id

                              select new
                              {
                                  name = c.ApplicationUser_ToUserId.FirstName + " " + c.ApplicationUser_ToUserId.LastName,
                                  read=c.IsRead,
                              };
            //var result = from c in tak select new string[] { Convert.ToString(c.ApplicationUser_ToUserId.FirstName + ' ' + c.ApplicationUser_ToUserId.LastName), Convert.ToString(c.IsRead),};
            return Json(new { aaData = tak }, JsonRequestBehavior.AllowGet);


        }
        private string newfunc(Announcement c)
        {
            string tu = "";
            var data = c.AnnouncementMember_EmailMessageIds;
            //foreach (var item in data)
            //{
                
            //    tu += item.ApplicationUser_ToUserId.FirstName + ' ' + item.ApplicationUser_ToUserId.LastName;
            //    tu += " , ";
            //}

            tu = "<a style='cursor:pointer !important;' onclick='expand(" + c.Id + ")'>" + "<i class='fa fa-check-square-o f18'>" + "</a>";
            //tu = tu.TrimEnd(' ');
            //tu = tu.TrimEnd(',');


            return tu;
        }

        //
        // GET: /Announcement/ModelBindIndex
        public ActionResult ModelBindIndex()
        {
            return ModelBind();
        }
        // GET: /Announcement/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Announcement ObjAnnouncement = db.Announcements.Find(id);
            if (ObjAnnouncement == null)
            {
                return HttpNotFound();
            }
            return View(ObjAnnouncement);
        }
        // GET: /Announcement/Create
        public ActionResult CreateOLd()
        {
            ViewBag.FromUserId = new SelectList(db.ApplicationUsers, "Id", "Username");

            return View();
        }

        // POST: /Announcement/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult CreateOLd(Announcement ObjAnnouncement)
        {
            if (ModelState.IsValid)
            {
                db.Announcements.Add(ObjAnnouncement);
                db.SaveChanges();
                return Redirect(TempData["ThisUrl"].ToString());
            }
            ViewBag.FromUserId = new SelectList(db.ApplicationUsers, "Id", "Username", ObjAnnouncement.FromUserId);

            return View(ObjAnnouncement);
        }






        [AuthorizationAndRoleFilter(accessRole = AccessRole.Announcement)]
        public ActionResult Create()
        {
            LoadBinding();
            return View();
        }

        private void LoadBinding()
        {
            var UsersList = db.ApplicationUsers.OrderBy(i => i.Department_DepartmentId.Title).ToArray(); 
            int cUserId = Convert.ToInt32(Env.GetUserInfo("userid"));

            StringBuilder sbUser = new StringBuilder();
            sbUser.Append("[");

            foreach (var item in UsersList.Where(i => i.Id != cUserId).ToArray())
            {
                sbUser.Append("{\"id\":\"" + item.Email + "\", \"name\":\"" + item.FirstName + " " + item.LastName + " " + "( " + item.Department_DepartmentId.Title + " )" + "\"},");
            }
            sbUser.Append("]");
            ViewBag.UserList = sbUser.ToString();




            StringBuilder sbDepartment = new StringBuilder();
            sbDepartment.Append("[");

            foreach (var item in db.Departments.OrderBy(x => x.Title).ToArray())
            {
                sbDepartment.Append("{\"id\":\"" + item.Title + "\", \"name\":\"" + item.Title + "\"},");
            }
            sbDepartment.Append("]");
            ViewBag.Departments = sbDepartment.ToString();

            StringBuilder sbFavoriteGroups = new StringBuilder();
            sbFavoriteGroups.Append("[");

            foreach (var item in db.FavoriteGroups.OrderBy(x => x.Name).ToArray())
            {
                sbFavoriteGroups.Append("{\"id\":\"" + item.Id + "\", \"name\":\"" + item.Name + "(" + prepareUsersName(item.Users) + ")" + "\"},");
            }
            sbFavoriteGroups.Append("]");
            ViewBag.FavoriteGroups = sbFavoriteGroups.ToString();

            ViewBag.FromUserId = new SelectList(UsersList, "Id", "Username", cUserId);
        }

        private string prepareUsersName(ICollection<ApplicationUser> users)
        {
            string usersName = "";
            foreach (var user in users)
            {
                usersName += user.CompleteName + ", ";
            }
            return usersName.Remove(usersName.Length - 2);
        }

        private string notify(int? id)
        {
            StringBuilder sb = new StringBuilder();
            //   int user = Convert.ToInt32(Env.GetUserInfo("userid"));
            var tak = db.AnnouncementMembers.Where(i => i.ToUserId == id && i.IsRead == false).ToArray();

            int intCount = tak.Count();

            sb.Append("<a href=\"#\" data-toggle=\"dropdown\" data-hover=\"dropdown\" data-close-others=\"true\"><i class=\"glyphicon glyphicon-warning-sign\"></i>");
            sb.Append("<span class=\"badge badge-danger badge-header\">" + intCount + "</span></a>");

            sb.Append("<ul class=\"dropdown-menu\" style=\"margin-right: -58px;\">");
            sb.Append("<li class=\"dropdown-header clearfix\"><p class=\"pull-left\">Bildirimler</p></li><li class=\"dropdown-body\"><ul style=\"margin-top:-30px\" class=\"dropdown-menu-list withScroll\" data-height=\"220\">");

            foreach (var item in tak)
            {

                sb.Append("<li class=\"clearfix\"><a href=\"/AnnouncementMember/Details/" + item.Id + "\"> <i class=\"fa fa-bullhorn \"></i>  " + (item.Announcement_EmailMessageId.Subject.Length > 20 ? item.Announcement_EmailMessageId.Subject.Substring(0, 25) + "..." : item.Announcement_EmailMessageId.Subject) + " </a> </li>");
            }

            //foreach (var item in events)
            //{
            //    sb.Append("<li> <a href=\"/EventMember/Details/" + item.EventMemberId + "\"> <i class=\"ion ion-ios7-person \"></i>" + item.Obj_Event.Subject + "</a> </li>");
            //}

            sb.Append("</ul></li><li class=\"dropdown-footer clearfix\"><a href=\"/AnnouncementMember/Index\">Tüm Bildirimleri Görüntüle</a></li> </ul>");

            ViewBag.sbs = sb.ToString();

            return sb.ToString();
        }



MassEmail/Views/Announcement/Create.cshtml
@model MassEmail.Models.Announcement

@{
    ViewBag.Title = "Bildirim Oluştur";
    if (Ajax.IsThisAjaxRequest())
    {
        Layout = null;
    }
}
@section ScriptsOrCss{
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    </head>

    <script src="~/Content/ckEditor/ckeditor.js"></script>
    <link href="~/Content/ckEditor/samples/sample.css" rel="stylesheet" />
    <link href="~/Content/tagsinput/magicsuggest-min.css" rel="stylesheet">
    <script src="~/Content/tagsinput/magicsuggest-min.js"></script>

}

<script type="text/javascript">
    $(function () {
        var ms1 = $('#ms1').magicSuggest({
            data: @Html.Raw(ViewBag.UserList),
            expandOnFocus:true
        });

        var departm = $('#departm').magicSuggest({
            data: @Html.Raw(ViewBag.Departments),
            });

        var favorite = $('#favorite').magicSuggest({
            data: @Html.Raw(ViewBag.FavoriteGroups),
            });

        $(ms1).on('selectionchange', function(){
            $("#toEmails").val(this.getValue());
        });

        $(departm).on('selectionchange', function(){
            $("#toDepEmails").val(this.getValue());
        });

        $(favorite).on('selectionchange', function(){
            $("#toFavoriteEmails").val(this.getValue());
        });
    });

    $(document).ready(function () {


        //$(document).mouseover(function () {
        //    $("#toEmails").val($("#ms1").text());
        //});

        //$(document).mouseover(function () {
        //    $("#toDepEmails").val($("#departm").text());
        //});

        //$("#ms1").click(function () {
        //    $("#toEmails").val($("#ms1").text());
        //});

        //$("#departm").click(function () {
        //    $("#toDepEmails").val($("#departm").text());
        //});


        $(".usr").click(function () {
            $("#ms1").show();
            $("#favorite").hide();
            $("#departm").hide();
        });

        $(".dep").click(function () {
            $("#ms1").hide();
            $("#favorite").hide();
            $("#departm").show();
        });

        $(".fav").click(function () {
            $("#ms1").hide();
            $("#favorite").show();
            $("#departm").hide();
        });

        //$("#usr input").click(function () {
        //    $("#ms1").show();
        //    $("#departm").hide();
        //});

        //$("#dpt input").click(function () {
        //    $("#ms1").hide();
        //    $("#departm").show();
        //});

        $('input:radio[name=sl]').change(function(){
            alert($('input[name=sl]:checked').val());
        })


    });


</script>
<section class="content-header">
    <h1>
        <meta charset="UTF-8" />
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    </h1>
</section>

@using (Html.BeginForm("Create", "Announcement", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
          <!-- Main content -->
    <section class="content">
        <!-- Small boxes (Stat box) -->
        <div class="row">
            <div class="panel">
                <div class="panel-header">
                    <h3> Bildirim Oluştur </h3>
                </div>
                <div role="form">
                    <div class="panel-content">

                        @if (ViewBag.Msg != null)
                        {
                            <div class="alert alert-danger alert-dismissable">
                                <i class="fa fa-ban"></i>
                                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                                <b>Uyarı! </b> @ViewBag.Msg
                            </div>
                        }
                        @if (ViewBag.Success != null)
                        {
                            <div class="alert alert-success alert-dismissable">
                                <i class="fa fa-ban"></i>
                                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                                <b>Başarıyla Oluşturuldu! </b> @ViewBag.Success
                            </div>
                        }
                        <div class="alert alert-danger alert-dismissable" style="display:@(this.ViewData.ModelState.IsValid ? "none" : "")">
                            <i class="fa fa-ban"></i>
                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>

                            @foreach (var key in this.ViewData.ModelState.Keys)
                            {
                                foreach (var err in this.ViewData.ModelState[key].Errors)
                                {
                                    <b>Uyarı! </b> @err.ErrorMessage
                                    <br />
                                }
                            }
                            @Html.ValidationSummary(true)
                        </div>
                        <div class="form-group">

                            <div class="switch-field" style="margin-left:-40px; margin-top:-45px; line-height:1.028571;">
                                <input class="usr" type="radio" id="switch_3_left" name="s1" value="Users" checked />
                                <label class="usr" for="switch_3_left">Kullanıcı</label>
                                <input class="dep" type="radio" id="switch_3_center" name="s1" value="Departments" />
                                <label class="dep" for="switch_3_center">Kurum</label>
                                <input class="fav" type="radio" id="switch_3_right" name="s1" value="FavoriteGroup" />
                                <label class="fav" for="switch_3_right">Favori Grup</label>
                            </div>

                            <table id="slUD" class="table">
                                <tr>
                                    <td id="usr"></td>
                                    <td id="dpt"></td>
                                    <td id="fv"></td>
                                </tr>
                            </table>
                        </div>
                        <div class="row" style="margin-top:-45px;">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Alıcı</label>
                                    <div id="ms1" class="form-control"></div>
                                    <div id="departm" class="form-control" style="display:none;"></div>
                                    <div id="favorite" class="form-control" style="display:none;"></div>
                                </div>
                            </div>
                            <div class="clear"></div>
                            <div class="form-group" style="display:none;">
                                @Html.LabelFor(model => model.FromUserId, new { @class = "" })
                                @Html.DropDownList("FromUserId", " -Seçiniz- ") @Html.ValidationMessageFor(model => model.FromUserId)

                                &nbsp;&nbsp; <a data-ajax="true" data-ajax-begin="prepareModalDialog('AddMore')" data-ajax-failure="clearModalDialog('AddMore');alert('Ajax call failed')" data-ajax-method="GET" data-ajax-mode="replace" data-ajax-success="openModalDialog('AddMore', 'Add')" data-ajax-update="#AddMore" href="~/ApplicationUser/Create">
                                    <img src="~/Content/ModelPopup/Plus.png" />
                                </a>
                            </div>
                            <div class="form-group" style="display:none;">
                                <input id="toEmails" type="text" name="toEmails" />
                                <input id="toDepEmails" type="text" name="toDepEmails" />
                                <input id="toFavoriteEmails" type="text" name="toFavoriteEmails" />
                                <input id="toboth" type="text" name="toboth">
                            </div>
                            <div class="row">
                                <div class="col-md-6 col-sm-12">
                                    <div class="form-group" style="margin-left:15px;">
                                        @Html.LabelFor(model => model.Subject, new { @class = "" })
                                        @Html.TextBoxFor(model => model.Subject, new { @class = "form-control", @placeholder = "Konu" }) @Html.ValidationMessageFor(model => model.Subject)
                                    </div>
                                </div>
                            </div>
                            <div class="clear"></div>
                            <div class="form-group" style="">
                                <input type="file" name="filesAttach" value="" />
                            </div>
                            <div class="clear"></div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.MailText, new { @class = "", @Style = "margin-left:15px;" })
                                @Html.TextAreaFor(model => model.MailText, new { @class = "ckeditor" }) @Html.ValidationMessageFor(model => model.MailText)
                            </div>
                            <div class="form-group">
                                @Html.Hidden("DateSend", DateTime.Now) @Html.ValidationMessageFor(model => model.DateSend)
                            </div>
                            <div class="form-group" style="display:none;">
                                <input type="hidden" value="false" name="IsDelete" />
                            </div>

                        </div>
                        <div class="box-footer">
                            <input type="submit" onclick="ShowProgressAnimation();" value="Oluştur" class="btn btn-primary m-l-20" />
                            @Html.ActionLink("Geçmiş", "Index", null, new { @class = "btn btn-primary" })
                        </div>
                        @*<div id="loading-div-background">
                            <div id="loading-div" class="ui-corner-all">
                                <img style="height:142px;width:142px;margin:30px;" src="/images/please_wait.gif" alt="Loading.." /><br>GÖNDERİLİYOR. LÜTFEN BEKLEYİNİZ...
                            </div>
                        </div>*@
                    </div>
                </div>
            </div>
        </div>
    </section>
}
<script type="text/javascript">
    $(document).ready(function (){
        $("#loading-div-background").css({ opacity: 1.0 });
    });

    function ShowProgressAnimation(){
        $("#loading-div-background").show();
    }
</script>

<style>
    .text-box.single-line {
        text-transform: uppercase;
    }
    
    .switch-field {
  font-family: "Lucida Grande", Tahoma, Verdana, sans-serif;
  padding: 40px;
	overflow: hidden;
}

.switch-title {
  margin-bottom: 6px;
}

.switch-field input {
  display: none;
}

.switch-field label {
  float: left;
}

.switch-field label {
  display: inline-block;
  width: 155px;
  background-color: #e4e4e4;
  color: rgba(0, 0, 0, 0.6);
  font-size: 14px;
  font-weight: normal;
  text-align: center;
  text-shadow: none;
  padding: 6px 14px;
  border: 1px solid rgba(0, 0, 0, 0.2);
  -webkit-box-shadow: inset 0 1px 3px rgba(0, 0, 0, 0.3), 0 1px rgba(255, 255, 255, 0.1);
  box-shadow: inset 0 1px 3px rgba(0, 0, 0, 0.3), 0 1px rgba(255, 255, 255, 0.1);
  -webkit-transition: all 0.1s ease-in-out;
  -moz-transition:    all 0.1s ease-in-out;
  -ms-transition:     all 0.1s ease-in-out;
  -o-transition:      all 0.1s ease-in-out;
  transition:         all 0.1s ease-in-out;
}

.switch-field label:hover {
	cursor: pointer;
}

.switch-field input:checked + label {
  background-color: #3AF;
  -webkit-box-shadow: none;
  box-shadow: none;
}

.switch-field label:first-of-type {
  border-radius: 4px 0 0 4px;
}

.switch-field label:last-of-type {
  border-radius: 0 4px 4px 0;
}
</style>


MassEmail/Views/Announcement/CreateOLd.cshtml
@model MassEmail.Models.Announcement

@{
    ViewBag.Title = "Create";
    if (Ajax.IsThisAjaxRequest())
    {
        Layout = null;
    }
}
@section ScriptsOrCss{ 
<script src="~/Content/ckEditor/ckeditor.js"></script>
<link href="~/Content/ckEditor/samples/sample.css" rel="stylesheet" />
}

<section class="content-header">
    <h1>
        @ViewBag.Title
        <small>Create</small>
    </h1>
</section>

@using (Html.BeginForm("CreateOLd", "Announcement", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
          <!-- Main content -->
    <section class="content">
        <!-- Small boxes (Stat box) -->
        <div class="row">
            <div class="col-xs-12">
                <div class="box box-solid box-primary">
                    <div class="box-header">
                        <h3 class="box-title">Fill Announcement Form</h3>
                    </div><!-- /.box-header -->
                    <!-- form start -->
                    <div role="form">
                        <div class="box-body">
                            <div class="alert alert-danger alert-dismissable" style="display:@(this.ViewData.ModelState.IsValid ? "none" : "")">
                                <i class="fa fa-ban"></i>
                                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>

                                @foreach (var key in this.ViewData.ModelState.Keys)
                                {
                                    foreach (var err in this.ViewData.ModelState[key].Errors)
                                    {
                                        <b>Alert! </b> @err.ErrorMessage
                                        <br />
                                    }
                                }
                                @Html.ValidationSummary(true)
                            </div>



                            <div class="form-group">
                                @Html.LabelFor(model => model.FromUserId, new { @class = "" })
                                @Html.DropDownList("FromUserId"," -Select- ") @Html.ValidationMessageFor(model => model.FromUserId)
                                
                                &nbsp;&nbsp; <a data-ajax="true" data-ajax-begin="prepareModalDialog('AddMore')" data-ajax-failure="clearModalDialog('AddMore');alert('Ajax call failed')" data-ajax-method="GET" data-ajax-mode="replace" data-ajax-success="openModalDialog('AddMore', 'Add')" data-ajax-update="#AddMore" href="~/ApplicationUser/Create">
                                     <img src="~/Content/ModelPopup/Plus.png" />
                                </a>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.Subject, new { @class = "" })
                                @Html.EditorFor(model => model.Subject) @Html.ValidationMessageFor(model => model.Subject)
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.MailText, new { @class = "" })
                                @Html.TextAreaFor(model => model.MailText, new { @class = "ckeditor" }) @Html.ValidationMessageFor(model => model.MailText)
                            </div>
                            <div class="form-group">
                                @Html.Hidden("DateSend", DateTime.Now) @Html.ValidationMessageFor(model => model.DateSend)
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.IsDelete, new { @class = "" })
                                @Html.EditorFor(model => model.IsDelete) @Html.ValidationMessageFor(model => model.IsDelete)
                            </div>




                        </div>
                        <div class="box-footer">
                            <input type="submit" value="Create" class="btn btn-primary" />
                            @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-primary" })
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
}




MassEmail/Views/Announcement/Edit.cshtml
@model MassEmail.Models.Announcement

@{
    ViewBag.Title = "Düzenle";
    if (Ajax.IsThisAjaxRequest())
    {
        Layout = null;
    }
}
@section ScriptsOrCss{
<head>
    <meta charset="UTF-8" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
</head>
<script src="~/Content/ckEditor/ckeditor.js"></script>
<link href="~/Content/ckEditor/samples/sample.css" rel="stylesheet" />
}
<section class="content-header">
    <h1>
        <meta charset="UTF-8" />
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        @ViewBag.Title
    </h1>
</section>
@using (Html.BeginForm("Edit", "Announcement", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <section class="content">
        <div class="row">
                <div class="panel">
                    <div class="panel-header">
                        <h3>Kullanıcı Düzenle</h3>
                    </div>
                    <div role="form">
                        <div class="panel-content">
                            <div class="alert alert-danger alert-dismissable" style="display:@(this.ViewData.ModelState.IsValid ? "none" : "")">
                                <i class="fa fa-ban"></i>
                                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                                @foreach (var key in this.ViewData.ModelState.Keys)
                                {
                                    foreach (var err in this.ViewData.ModelState[key].Errors)
                                    {
                                        <b>Uyarı! </b> @err.ErrorMessage
                                        <br />
                                    }
                                }
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.FromUserId, new { @class = "" })
                                @Html.DropDownList("FromUserId"," -Seçiniz- ") @Html.ValidationMessageFor(model => model.FromUserId)
                                
                                &nbsp;&nbsp; <a data-ajax="true" data-ajax-begin="prepareModalDialog('AddMore')" data-ajax-failure="clearModalDialog('AddMore');alert('Ajax call failed')" data-ajax-method="GET" data-ajax-mode="replace" data-ajax-success="openModalDialog('AddMore', 'Add')" data-ajax-update="#AddMore" href="~/ApplicationUser/Create">
                                     <img src="~/Content/ModelPopup/Plus.png" />
                                </a>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.Subject, new { @class = "" })
                                @Html.EditorFor(model => model.Subject) @Html.ValidationMessageFor(model => model.Subject)
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.MailText, new { @class = "" })
                                @Html.TextAreaFor(model => model.MailText, new { @class = "ckeditor" }) @Html.ValidationMessageFor(model => model.MailText)
                            </div>
                            <div class="form-group">
                                @Html.Hidden("DateSend", DateTime.Now) @Html.ValidationMessageFor(model => model.DateSend)
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.IsDelete, new { @class = "" })
                                @Html.EditorFor(model => model.IsDelete) @Html.ValidationMessageFor(model => model.IsDelete)
                            </div>


                        </div><!-- /.box-body -->
                        <div class="box-footer">
                            <input type="submit" value="Kaydet" class="btn btn-primary" />
                            @Html.ActionLink("Liste", "Index", null, new { @class = "btn btn-primary" })
                        </div>
                    </div>
                </div>
        </div>
    </section>

}

